package com.alexcupsa.wifithermal.core.data.repository

import android.content.Context
import com.alexcupsa.wifithermal.core.model.audit.AuthorizationScope
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.serialization.json.Json
import java.io.File
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Loads the operator-supplied authorization manifest from a file in the
 * app's internal storage. The manifest defines what's in scope; without
 * one, the app falls back to a deny-all default and prompts the operator
 * to provide it.
 *
 * The manifest is intentionally a plain JSON file the operator drops into
 * the app's files dir (or imports through the Authorization screen). It is
 * NOT generated by the app itself — that would defeat the point of having
 * an external authorization record.
 */
@Singleton
class AuthorizationManifestRepository @Inject constructor(
    @ApplicationContext private val context: Context,
) {
    private val file: File by lazy { File(context.filesDir, MANIFEST_FILE) }

    private val _scope = MutableStateFlow<AuthorizationScope?>(null)
    val scope: StateFlow<AuthorizationScope?> = _scope.asStateFlow()

    init {
        runCatching { load() }
    }

    fun load(): AuthorizationScope? {
        if (!file.exists()) {
            _scope.value = null
            return null
        }
        val parsed = runCatching { json.decodeFromString<AuthorizationScope>(file.readText()) }
            .getOrNull()
        _scope.value = parsed
        return parsed
    }

    fun save(scope: AuthorizationScope) {
        file.writeText(json.encodeToString(AuthorizationScope.serializer(), scope))
        _scope.value = scope
    }

    fun clear() {
        file.delete()
        _scope.value = null
    }

    fun isAuthorized(now: Long = System.currentTimeMillis()): Boolean {
        val current = _scope.value ?: return false
        return !current.isExpired(now)
    }

    companion object {
        private const val MANIFEST_FILE = "authorization_manifest.json"
        private val json = Json { prettyPrint = true; ignoreUnknownKeys = true }
    }
}
